-- ═══════════════════════════════════════════════════════════════════════
--  UYGULANMADI — BEKLEYEN MIGRATION
-- ═══════════════════════════════════════════════════════════════════════
--
-- ⚠️ Bu dosya BİLEREK `prisma/migrations/` ALTINDA DEĞİL.
--    CI `prisma migrate deploy` çalıştırıyor (.github/workflows/ci.yml);
--    dosya gerçek migration klasöründe olsaydı bir sonraki boru hattında
--    KENDİLİĞİNDEN uygulanırdı. Oysa bu şema değişikliği, henüz açılmamış
--    (ve birim ekonomisi hesaplanmamış) bir özelliğe aittir — video sanal
--    deneme. Bkz. docs/ozellik-yol-haritasi.md → "Faz 3 — video try-on".
--
-- NİÇİN GEREKLİ
-- `AiUsageLog.feature` alanı `AiFeature` enum'ıdır ve maliyet paneli ile
-- bütçe sorguları bu alana göre gruplanır. Video harcamasını mevcut 'TRYON'
-- değerine yazmak, iki farklı birim maliyeti (≈0,06 $ ve ≈0,50 $) tek
-- ortalamada eritirdi: Faz 3 kararının dayanacağı sayı, tam da ölçülmek
-- istendiği anda bozulmuş olurdu. Video için AYRI günlük bütçe kovası da
-- (AI_VIDEO_DAILY_BUDGET_USD) yalnızca bu filtre varsa ölçülebilir.
--
-- ÖZELLİK AÇILIRKEN YAPILACAKLAR — SIRAYLA
--   1. packages/db/prisma/schema.prisma → `enum AiFeature` içine VIDEO_TRYON
--      ekle. (Şema ile migration birlikte gitmezse CI'daki
--      `prisma migrate status` adımı sapma bildirir.)
--   2. Bu klasörü `packages/db/prisma/migrations/` altına taşı.
--   3. packages/config/src/ai-budget.ts → `AiFeature` birleşimine ve
--      `ESTIMATED_UNIT_COST_MICRO_USD` tablosuna VIDEO_TRYON ekle
--      (TS tarafı Prisma enum'ından türemiyor, elle güncelleniyor).
--   4. `pnpm --filter @vt/db migrate` ile uygula.
--
-- ⚠️ GERİ ALINAMAZ: PostgreSQL'de bir enum değeri KALDIRILAMAZ (tipin
--    yeniden yaratılması gerekir). Bu yüzden değer, özellik gerçekten
--    açılmaya karar verildiğinde eklenmelidir — "şimdiden dursun" diye değil.
--
-- ── KARAR (2026-08-12): UYGULANMADI, burada kalmaya devam ediyor. ─────────
--
-- Yukarıdaki uyarı bugün de geçerli olduğu için aynen korundu:
--   • `AI_VIDEO_TRYON_ENABLED` varsayılanı FALSE ve `FAL_VIDEO_TRYON_MODEL`
--     BOŞ → fabrika `Unconfigured` dönüyor (adapters/ai/video-tryon.ts).
--     Yani bu değeri YAZABİLECEK TEK BİR KOD YOLU BİLE YOK; enum bugün
--     eklenirse ilk satırını belirsiz bir gelecekte alır.
--   • Kayıp yok: yazılamayan bir maliyet yok, çünkü harcanan para da yok.
--   • docs/ozellik-yol-haritasi.md → Faz 3 karar sırasını açıkça yazıyor:
--     birim ekonomi ölçülmeden video'ya girilmez. Şemayı önden açmak, geri
--     ALINAMAZ bir adımı ölçümden ÖNCE atmak olurdu.
--
-- ⚠️ KARŞILAŞTIRMA — neden SEARCH_NL uygulandı da bu uygulanmadı: doğal dil
--    aramada para ŞU AN harcanıyor ve deftere yazılamıyordu (gerçekleşen
--    kayıp). Burada harcama yok; yalnızca gelecekte olma ihtimali var.
--    Geri alınamaz bir değişikliğin bedeli, ihtimalle değil GERÇEKLEŞEN
--    ihtiyaçla ödenir.
--
-- ⚠️ SONRA TAŞINIRKEN: bu klasörün damgası 20260812090000, oysa
--    `migrations/20260812094700_ai_feature_search_nl` UYGULANDI. Taşırken
--    klasörü O ANIN damgasıyla yeniden adlandırın; aksi hâlde uygulanmış bir
--    migration'ın ÖNÜNE sıralanır (deploy yine çalışır, ama geçmiş yanıltıcı
--    okunur).

-- PostgreSQL 17 (CI: pgvector/pgvector:pg17) `ALTER TYPE ... ADD VALUE`
-- ifadesini transaction içinde kabul eder; yeni değer aynı transaction'da
-- KULLANILAMAZ, bu migration da kullanmıyor.
ALTER TYPE "AiFeature" ADD VALUE IF NOT EXISTS 'VIDEO_TRYON';
